05 - Cadastro - CRUD/crudBD/crudBD/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('crud/', include('crudapp.urls')),
]

05 - Cadastro - CRUD/crudBD/crudapp/urls.py
from django.urls import path, include
from . import views

app_name = 'crudapp'
urlpatterns = [
    # Páginas de visualização
    path('', views.MainPageView.as_view(), name='main_page'),
    path('user_list/', views.UserListView.as_view(), name='user_list_page'),
    path('new_user/', views.NewUserView.as_view(), name='new_user_page'),
    path('edit_user/<slug:user_pk>/', views.EditUserView.as_view(), name='edit_user_page'),
    path('delete_user/<slug:user_pk>/', views.DeleteUserView.as_view(), name='delete_user_page'),
    path('add_friends/<slug:user_pk>/', views.AddFriendView.as_view(), name='add_friend_page'),
    path('add_friend/<slug:user_pk>/<slug:user_pk2>/', views.add_friend, name='add_friend'),
    path('add_movie/<slug:user_pk>/', views.AddMovieView.as_view(), name='add_movie_page'),
    path('add_music/<slug:user_pk>/', views.AddMusicView.as_view(), name='add_music_page'),
    path('data/',views.Data.as_view(), name = 'data'),

    # Para importar tabelas csv nos bancos (não tem acesso pela interface)
    path('import_db_users/', views.import_db_users, name='import_db_users'),
    path('import_db_friends/', views.import_db_friends, name='import_db_friends'),
    path('import_db_likes_movie/', views.import_db_likes_movie, name='import_db_likes_movie'),
    path('import_db_likes_music/', views.import_db_likes_music, name='import_db_likes_music'),
]

05 - Cadastro - CRUD/crudBD/crudapp/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.


class User(models.Model):
    class Meta:
        db_table = 'user'
    link = models.CharField(max_length=200, null=True)
    nome = models.CharField(max_length=100, null=True)
    cidade = models.CharField(max_length=30, null=True)
    aniversario = models.CharField(max_length=10, default='12/31/1900')


class Friends(models.Model):
    class Meta:
        db_table = 'friends'
        unique_together = (('user1', 'user2'),)
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='friend', null=True)


class LikesMovie(models.Model):
    class Meta:
        db_table = 'likes_movie'

    user1 = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    movie_link = models.CharField(max_length=200, null=True)
    rating = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)])


class LikesMusic(models.Model):
    class Meta:
        db_table = 'likes_music'

    user1 = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    band_link = models.CharField(max_length=200, null=True)
    rating = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)])

05 - Cadastro - CRUD/crudBD/crudapp/forms.py
from .models import User
from django.forms import ModelForm


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = '__all__'


class EditUserForm(UserForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['link'].widget.attrs['readonly'] = True

    def clean_link(self):
        instance = getattr(self, 'instance', None)
        if instance:
            return instance.link
        else:
            return self.cleaned_data.get('link', None)

05 - Cadastro - CRUD/crudBD/crudapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from .models import User, Friends
from .forms import EditUserForm
from .resources import *
from tablib import Dataset



class Data(View):
    template_name = 'crudapp/data.html'
    def get_media_music(self):
        list_music=LikesMusic.objects.filter()
        nota =0
        i =0
        for music in list_music:
            nota = nota+music.rating
            i = i+1
        return nota/i

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['music_list'] = LikesMusic.objects.filter()
        context['media'] = self.get_media_music()
        return context

class UserListView(ListView):
    model = User
    template_name = 'crudapp/list_users.html'
    ordering = ['nome']


class NewUserView(CreateView):
    model = User
    fields = '__all__'
    template_name = 'crudapp/form_user.html'
    success_url = reverse_lazy('crudapp:main_page')


class MainPageView(View):
    def get(self, request):
        return render(request, 'crudapp/main_page.html', {})


class EditUserView(UpdateView):
    model = User
    form_class = EditUserForm
    template_name = 'crudapp/edit_user.html'
    slug_field = 'pk'
    slug_url_kwarg = 'user_pk'
    success_url = reverse_lazy('crudapp:user_list_page')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['music_list'] = LikesMusic.objects.filter(user1=self.object.pk)
        context['movie_list'] = LikesMovie.objects.filter(user1=self.object.pk)
        return context



class DeleteUserView(DeleteView):
    model = User
    success_url = reverse_lazy('crudapp:user_list_page')
    slug_field = 'pk'
    slug_url_kwarg = 'user_pk'


class AddFriendView(View):
    def get(self, request, user_pk):
        all_users = User.objects.all().order_by('nome')
        try:
            friends = [friendship.user2.pk for friendship in Friends.objects.filter(user1=user_pk)]
            friends = all_users.filter(pk__in=friends).order_by('nome')
        except Friends.DoesNotExist:
            friends = []
        user = all_users.get(pk=user_pk)
        not_friends = []
        for other_user in all_users:
            if other_user.link != user.link and other_user not in friends:
                not_friends.append(other_user)
        user = all_users.get(pk=user_pk)
        return render(request, 'crudapp/add_friend.html', {'user': user, 'friends': friends, 'not_friends': not_friends})


class AddMusicView(CreateView):
    model = LikesMusic
    fields = ('band_link', 'rating')
    template_name = 'crudapp/add_music.html'

    def get(self, request, user_pk):
        # Inserimos self.user_pk pra que consigamos acessar de 'get_context_data'
        self.user_pk = user_pk
        return super().get(request)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        # Inserimos o conteúdo de user aqui para podermos acessar no template.
        data['user'] = User.objects.get(pk=self.user_pk)
        return data

    def post(self, request, user_pk):
        # Inserimos self.user_pk pra que consigamos acessar de 'form_valid'
        self.user_pk = user_pk
        return super().post(request)

    def form_valid(self, form):
        form.instance.user1 = User.objects.get(pk=self.user_pk)
        form.save()
        return redirect('crudapp:edit_user_page', user_pk=self.user_pk)


class AddMovieView(CreateView):
    model = LikesMovie
    fields = ('movie_link', 'rating')
    template_name = 'crudapp/add_movie.html'

    def get(self, request, user_pk):
        # Inserimos self.user_pk pra que consigamos acessar de 'get_context_data'
        self.user_pk = user_pk
        return super().get(request)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        # Inserimos o conteúdo de user aqui para podermos acessar no template.
        data['user'] = User.objects.get(pk=self.user_pk)
        return data

    def post(self, request, user_pk):
        # Inserimos self.user_pk pra que consigamos acessar de 'form_valid'
        self.user_pk = user_pk
        return super().post(request)

    def form_valid(self, form):
        form.instance.user1 = User.objects.get(pk=self.user_pk)
        form.save()
        return redirect('crudapp:edit_user_page', user_pk=self.user_pk)


def add_friend(request, user_pk, user_pk2):
    user1 = User.objects.get(pk=user_pk)
    user2 = User.objects.get(pk=user_pk2)
    Friends.objects.create(user1=user1, user2=user2)
    return redirect('crudapp:add_friend_page', user_pk=user_pk)




def import_db_users(request):
    if request.method == 'POST':
        user_resource = UserResource()

        new_users = request.FILES['myfile']
        s = new_users.read().decode("utf-8")
        s_list = s.split('\r')
        header = s_list.pop(0)  # Header
        header += ',id'  # Adiciona id ao header (necessário)
        s_list.pop()  # '\n' (lixo)
        dataset = Dataset(headers=header.split(','))
        for ind, entry in enumerate(s_list):
            s_list[ind] = entry.replace('\n', '').split(',')
            s_list[ind].append('')  # Para o campo id que será preenchido
            dataset.append(s_list[ind])

        result = user_resource.import_data(dataset, dry_run=True, raise_errors=True)  # Test the data import
        print("HAS ERRORS:", result.has_errors())

        if not result.has_errors():
            user_resource.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'crudapp/import_db.html')

def import_db_friends(request):
    if request.method == 'POST':
        friends_resource = FriendsResource()
        new_friends = request.FILES['myfile']
        s = new_friends.read().decode("utf-8")
        s_list = s.split('\r')
        header = s_list.pop(0)  # Header
        header += ',id'  # Adiciona id ao header (necessário)
        s_list.pop()  # '\n' (lixo)
        dataset = Dataset(headers=header.split(','))
        for ind, entry in enumerate(s_list):
            s_list[ind] = entry.replace('\n', '').split(',')
            s_list[ind].append('')  # Para o campo id que será preenchido

        for ind, entry in enumerate(s_list):
            try:
                s_list[ind][0] = User.objects.get(link=entry[0]).pk
                s_list[ind][1] = User.objects.get(link=entry[1]).pk
            except User.DoesNotExist:
                continue
            dataset.append(s_list[ind])

        result = friends_resource.import_data(dataset, dry_run=True, raise_errors=True)  # Test the data import
        print("HAS ERRORS:", result.has_errors())

        if not result.has_errors():
            friends_resource.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'crudapp/import_db.html')

def import_db_likes_movie(request):
    if request.method == 'POST':
        movie_resource = LikesMovieResource()
        new_movies = request.FILES['myfile']
        s = new_movies.read().decode("utf-8")
        s_list = s.split('\r')
        header = s_list.pop(0)  # Header
        header += ',id'  # Adiciona id ao header (necessário)
        s_list.pop()  # '\n' (lixo)
        dataset = Dataset(headers=header.split(','))
        for ind, entry in enumerate(s_list):
            s_list[ind] = entry.replace('\n', '').split(',')
            s_list[ind].append('')  # Para o campo id que será preenchido

        for ind, entry in enumerate(s_list):
            try:
                s_list[ind][0] = User.objects.get(link=entry[0]).pk
            except User.DoesNotExist:
                continue
            dataset.append(s_list[ind])

        result = movie_resource.import_data(dataset, dry_run=True, raise_errors=True)  # Test the data import
        print("HAS ERRORS:", result.has_errors())

        if not result.has_errors():
            movie_resource.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'crudapp/import_db.html')

def import_db_likes_music(request):
    if request.method == 'POST':
        music_resource = LikesMusicResource()
        new_music = request.FILES['myfile']
        s = new_music.read().decode("utf-8")
        s_list = s.split('\r')
        header = s_list.pop(0)  # Header
        header += ',id'  # Adiciona id ao header (necessário)
        s_list.pop()  # '\n' (lixo)
        dataset = Dataset(headers=header.split(','))
        for ind, entry in enumerate(s_list):
            s_list[ind] = entry.replace('\n', '').split(',')
            s_list[ind].append('')  # Para o campo id que será preenchido

        for ind, entry in enumerate(s_list):
            try:
                s_list[ind][0] = User.objects.get(link=entry[0]).pk
            except User.DoesNotExist:
                continue
            dataset.append(s_list[ind])

        result = music_resource.import_data(dataset, dry_run=True, raise_errors=True)  # Test the data import
        print("HAS ERRORS:", result.has_errors())

        if not result.has_errors():
            music_resource.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'crudapp/import_db.html')

05 - Cadastro - CRUD/crudBD/crudapp/templates/crudapp/add_friend.html
{% extends 'crudapp/base_generic.html' %}

{% block title %}<h1>Adicionar Amigos</h1>{% endblock %}

{% block body %}

    <p>Adicionando amigos para o usuário: {{ user.nome }}</p>

    <h3>Amigos</h3>
    <ul>
    {% for friend in friends %}
        <li>{{ friend.nome }} ({{ friend.link }})</li>
    {% empty %}
        <li>Você não tem amigos</li>
    {% endfor %}
    </ul>

    <h3>Outros Usuários</h3> <p>(clique para adicionar)</p>
    <ul>
    {% for other_user in not_friends %}
        <li><a href="{% url 'crudapp:add_friend' user.pk other_user.pk %}">{{ other_user.nome }} ({{ other_user.link }})</a></li>
    {% empty %}
        <li>Você é amigo de todas as pessoas cadastradas na rede</li>
    {% endfor %}
    </ul>

    <form action="{% url 'crudapp:edit_user_page' user.pk %}">
        <button type="submit">Voltar</button>
    </form>

{% endblock %}

05 - Cadastro - CRUD/crudBD/crudapp/templates/crudapp/add_movie.html
{% extends 'crudapp/base_generic.html' %}

{% block title %}<h1>Adicionar Filme</h1>{% endblock %}

{% block body %}

    <p>Adicionando filmes para o usuário: {{ user.nome }}</p>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar" />
    </form>

    <form action="{% url 'crudapp:edit_user_page' user.pk %}">
        <button type="submit">Voltar</button>
    </form>

{% endblock %}

05 - Cadastro - CRUD/crudBD/crudapp/templates/crudapp/add_music.html
{% extends 'crudapp/base_generic.html' %}

{% block title %}<h1>Adicionar Música</h1>{% endblock %}

{% block body %}

    <p>Adicionando músicas para o usuário: {{ user.nome }}</p>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar" />
    </form>

    <form action="{% url 'crudapp:edit_user_page' user.pk %}">
        <button type="submit">Voltar</button>
    </form>

{% endblock %}

05 - Cadastro - CRUD/crudBD/crudapp/templates/crudapp/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block page_title %}CRUD{% endblock %}</title>

    <style>

    .error_message {
        color: red;
        font-weight: bold;
    }

    </style>

    {% block style %}
    {% endblock %}

    {% block script %}
    {% endblock %}

    {% block head %}
    {% endblock %}

</head>
<body>

{% block title %}{% endblock %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <li class="error_message">{{ message }}</li>
        {% else %}
            <li>{{ message }}</li>
        {% endif %}
    {% endfor %}
</ul>
{% endif %}

{% block body %}
{% endblock %}
</body>
</html>

05 - Cadastro - CRUD/crudBD/crudapp/templates/crudapp/data.html
{% extends 'crudapp/base_generic.html' %}

{% block title %}<h1>Estatísticas</h1>{% endblock %}

{% block body %}
    <ul>
        <p>{{media}}</p>
         <table>
            <tr>
                <th>Link da Música</th>
                <th>Nota</th>
            </tr>
        {% for music in music_list %}
            <tr>
                <td align="center">{{ music.band_link }}</td>
                <td align="center">{{ music.rating }}</td>
            </tr>
        {% endfor %}
         </table>
    </ul>
{% endblock %}

05 - Cadastro - CRUD/crudBD/crudapp/templates/crudapp/edit_user.html
{% extends 'crudapp/form_user.html' %}

{% block title %}<h1>Página de {{ user.nome }}</h1>{% endblock %}

{% block style %}
    <style>
         table, th, td {
            border: 1px solid black;
         }
    </style>
{% endblock %}

{% block more_options %}

    <h3>Filmes adicionados</h3>
    {% if movie_list %}
        <table>
            <tr>
                <th>Link do Filme</th>
                <th>Nota</th>
            </tr>
        {% for movie in movie_list %}
            <tr>
                <td align="center">{{ movie.movie_link }}</td>
                <td align="center">{{ movie.rating }}</td>
            </tr>
        {% endfor %}
         </table>
    {% else %}
        <p>Você não adicionou filmes.</p>
    {% endif %}
    <br>
    <form action="{% url 'crudapp:add_movie_page' user.pk %}">
        <button type="submit">Adicionar Filme</button>
	</form>

    <h3>Músicas adicionadas</h3>
    {% if music_list %}
        <table>
            <tr>
                <th>Link da Música</th>
                <th>Nota</th>
            </tr>
        {% for music in music_list %}
            <tr>
                <td align="center">{{ music.band_link }}</td>
                <td align="center">{{ music.rating }}</td>
            </tr>
        {% endfor %}
         </table>
    {% else %}
        <p>Você não adicionou músicas.</p>
    {% endif %}
    <br>
    <form action="{% url 'crudapp:add_music_page' user.pk %}">
        <button type="submit">Adicionar Música</button>
	</form>
    <br>

    <form action="{% url 'crudapp:add_friend_page' user.pk %}">
        <button type="submit">Adicionar Amigo</button>
	</form>
    <br>

    <form action="{% url 'crudapp:delete_user_page' user.pk %}">
        <button type="submit">Deletar Usuário</button>
	</form>
    <br>

{% endblock %}

{% block voltar %}
    <form action="{% url 'crudapp:user_list_page' %}">
        <button type="submit">Voltar</button>
    </form>
{% endblock %}

05 - Cadastro - CRUD/crudBD/crudapp/templates/crudapp/form_user.html
{% extends 'crudapp/base_generic.html' %}

{% block title %}<h1>CRUD</h1>{% endblock %}

{% block body %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar" />
    </form>

    {% block more_options %}
    {% endblock %}

    {% block voltar %}
        <form action="{% url 'crudapp:main_page' %}">
            <button type="submit">Voltar</button>
        </form>
    {% endblock %}
{% endblock %}

05 - Cadastro - CRUD/crudBD/crudapp/templates/crudapp/import_db.html
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

05 - Cadastro - CRUD/crudBD/crudapp/templates/crudapp/list_users.html
{% extends 'crudapp/base_generic.html' %}

{% block title %}<h1>Lista de Usuários</h1>{% endblock %}

{% block body %}
    <p>Clique em um nome para mais opções</p>
    <ul>
    {% for user in object_list %}
        <li><a href="{% url 'crudapp:edit_user_page' user.pk %}">{{ user.nome }}</a></li>
    {% empty %}
        <li>Nenhum usuário criado.</li>
    {% endfor %}
    </ul>

    <form action="{% url 'crudapp:main_page' %}">
        <button type="submit">Voltar</button>
	</form>
{% endblock %}

05 - Cadastro - CRUD/crudBD/crudapp/templates/crudapp/main_page.html
{% extends 'crudapp/base_generic.html' %}

{% block title %}<h1>CRUD</h1>{% endblock %}

{% block body %}
    <ul>
        <li><a href="{% url 'crudapp:user_list_page' %}">Usuários na Rede</a></li>
        <li><a href="{% url 'crudapp:new_user_page' %}">Cadastrar Usuário</a></li>
        <li><a href ="{% url 'crudapp:data' %}">Estatísticas</a></li>
    </ul>
{% endblock %}

05 - Cadastro - CRUD/crudBD/crudapp/templates/crudapp/user_confirm_delete.html
{% extends 'crudapp/base_generic.html' %}

{% block title %}<h1>Deletar Usuário</h1>{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        <p>Tem certeza que deseja deletar o usuário "{{ user.nome }}" ({{ user.link }})?</p>
        <input type="submit" value="Deletar">
    </form>

    <form action="{% url 'crudapp:edit_user_page' user.pk %}">
        <button type="submit">Voltar</button>
    </form>
{% endblock %}