07- Análise e Data Mining/crudBD/crudBD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('crudapp.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

07- Análise e Data Mining/crudBD/crudapp/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'crudapp'




urlpatterns = [
    # Páginas de visualização
    path('', views.MainPageView.as_view(), name='main_page'),
    path('user_list/', views.UserListView.as_view(), name='user_list_page'),
    path('new_user/', views.NewUserView.as_view(), name='new_user_page'),
    path('user_page/<slug:username>/', views.ShowUserView.as_view(), name='user_page'),
    path('edit_user/<slug:user_pk>/', views.EditUserView.as_view(), name='edit_user_page'),
    path('delete_user/<slug:user_pk>/', views.DeleteUserView.as_view(), name='delete_user_page'),
    path('add_friends/<slug:user_pk>/', views.AddFriendView.as_view(), name='add_friend_page'),
    path('add_friend/<slug:user_pk>/<slug:user_pk2>/', views.add_friend, name='add_friend'),
    path('add_movie/<slug:user_pk>/', views.AddMovieView.as_view(), name='add_movie_page'),
    path('add_movie/<slug:user_pk>/<slug:movie_pk>/', views.AddMovieView.as_view(), name='add_movie_page'),
    path('add_music/<slug:user_pk>/', views.AddMusicView.as_view(), name='add_music_page'),
    path('add_music/<slug:user_pk>/<slug:music_pk>/', views.AddMusicView.as_view(), name='add_music_page'),
    path('statistics/', views.StatisticsPageView.as_view(), name='statistics_page'),
    path('popularity/', views.PopularityPageView.as_view(), name='popularity_page'),
    path('statistics/average', views.AveragePageView.as_view(), name='average_page'),
    path('statistics/ratings', views.RatingsPageView.as_view(), name='ratings_page'),
    path('statistics/conhecidos', views.ConhecidosPageView.as_view(), name='conhecidos_page'),
    path('statistics/graphics', views.GraphicsPageView.as_view(), name='graphics_page'),
    path('media/<slug:image_name>', views.GraphicsPageView.as_view(), name='graphics_page'),

    # Páginas de Login
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),


    # Para importar tabelas csv nos bancos (não tem acesso pela interface)
    path('import_db_users/', views.import_db_users, name='import_db_users'),
    path('import_db_friends/', views.import_db_friends, name='import_db_friends'),
    path('import_db_likes_movie/', views.import_db_likes_movie, name='import_db_likes_movie'),
    path('import_db_likes_music/', views.import_db_likes_music, name='import_db_likes_music'),




]

07- Análise e Data Mining/crudBD/crudapp/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User as DjangoUser
from django.urls import reverse
import os
from uuid import uuid4


def path_and_rename(instance, filename):
    upload_to = ''
    ext = filename.split('.')[-1]
    # get filename
    if instance.pk:
        filename = '{}.{}'.format(instance.username, ext)
    else:
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
    # return the whole path to the file
    return os.path.join(upload_to, filename)


class User(AbstractUser):
    class Meta:
        db_table = 'user'
    hometown = models.CharField(max_length=30, null=True)
    birthday = models.CharField(max_length=10, default='12/31/1900')
    profile_pic = models.ImageField(upload_to=path_and_rename, default='no_pic.jpg')

    def get_absolute_url(self):
        return reverse('crudapp:user_page', kwargs={'username': self.username})


class Friends(models.Model):
    class Meta:
        db_table = 'friends'
        unique_together = (('user1', 'user2'),)
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='friend', null=True)


class Movie(models.Model):
    class Meta:
        db_table = 'movie'

    link = models.CharField(max_length=200, null=True)
    nome = models.CharField(max_length=200, null=True)
    lancamento = models.CharField(max_length=50, null=True)
    diretor = models.CharField(max_length=200, null=True)
    genero = models.CharField(max_length=200, null=True)
    img_link = models.CharField(max_length=500, null=True)


class Music(models.Model):
    class Meta:
        db_table = 'music'

    nome = models.CharField(max_length=200, null=True)
    seguidores = models.CharField(max_length=50, null=True)
    genero = models.CharField(max_length=200, null=True)
    spotify = models.CharField(max_length=200, null=True)
    img_link = models.CharField(max_length=500, null=True)


class LikesMovie(models.Model):
    class Meta:
        db_table = 'likes_movie'
        unique_together = ('user1', 'movie')

    user1 = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, null=True)
    rating = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)])


class LikesMusic(models.Model):
    class Meta:
        db_table = 'likes_music'
        unique_together = ('user1', 'music')

    user1 = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    music = models.ForeignKey(Music, on_delete=models.CASCADE, null=True)
    rating = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)])

07- Análise e Data Mining/crudBD/crudapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms import ModelForm, Textarea, CharField, TextInput, DateInput, DateField, Form, BooleanField, ModelChoiceField, ChoiceField, MultipleChoiceField, CheckboxSelectMultiple
from django.contrib.auth import get_user_model
from .models import LikesMovie,LikesMusic
User = get_user_model()


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'hometown', 'birthday', 'profile_pic')


class EditUserForm(UserForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['readonly'] = True

    def clean_link(self):
        instance = getattr(self, 'instance', None)
        if instance:
            return instance.link
        else:
            return self.cleaned_data.get('link', None)


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'hometown', 'birthday', 'password1', 'password2',
                  'profile_pic')
        labels = {'profile_pic': 'Profile Picture', }


class AddMovieForm(ModelForm):
    movie_link = CharField(required=True)

    class Meta:
        model = LikesMovie
        fields = ('rating', )

class AddMusicForm(ModelForm):
    music_name = CharField(required=True)

    class Meta:
        model = LikesMusic
        fields = ('rating', )

07- Análise e Data Mining/crudBD/crudapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from django.template.loader import get_template
from django.http import HttpResponse
from .resources import *
from tablib import Dataset
from django.db.models import Avg, StdDev
from django.db import connection
import matplotlib
matplotlib.use('Agg')
from matplotlib import pyplot as plt
import numpy as np
from math import pi
import base64, io
import csv
from bs4 import BeautifulSoup
import requests
import xml.etree.cElementTree as ET
from bootstrap_modal_forms.generic import BSModalLoginView, BSModalCreateView, BSModalUpdateView, BSModalDeleteView
from django.contrib.auth import login, authenticate, logout as django_logout
from .forms import LoginForm, SignUpForm, AddMovieForm, EditUserForm,AddMusicForm
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from .models import Movie, Music

from bs4 import BeautifulSoup
import requests
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
client_credentials_manager = SpotifyClientCredentials(client_id='f3754bb8fb9d458d8cb25591f58e77b9',
                                                               client_secret='4daeb28a153c4a03854052d7ac0a11dd')

sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

def logout(request):
    django_logout(request)
    return redirect('crudapp:main_page')

def add_friend(request, user_pk, user_pk2):
    user1 = User.objects.get(pk=user_pk)
    user2 = User.objects.get(pk=user_pk2)
    Friends.objects.create(user1=user1, user2=user2)
    return redirect('crudapp:add_friend_page', user_pk=user_pk)

def import_db_users(request):
    if request.method == 'POST':
        user_resource = UserResource()

        new_users = request.FILES['myfile']
        s = new_users.read().decode("utf-8")
        s_list = s.split('\r')
        header = s_list.pop(0)  # Header
        header += ',id'  # Adiciona id ao header (necessário)
        s_list.pop()  # '\n' (lixo)
        dataset = Dataset(headers=header.split(','))
        for ind, entry in enumerate(s_list):
            s_list[ind] = entry.replace('\n', '').split(',')
            s_list[ind].append('')  # Para o campo id que será preenchido
            dataset.append(s_list[ind])

        result = user_resource.import_data(dataset, dry_run=True, raise_errors=True)  # Test the data import
        print("HAS ERRORS:", result.has_errors())

        if not result.has_errors():
            user_resource.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'crudapp/import_db.html')

def import_db_friends(request):
    if request.method == 'POST':
        friends_resource = FriendsResource()
        new_friends = request.FILES['myfile']
        s = new_friends.read().decode("utf-8")
        s_list = s.split('\r')
        header = s_list.pop(0)  # Header
        header += ',id'  # Adiciona id ao header (necessário)
        s_list.pop()  # '\n' (lixo)
        dataset = Dataset(headers=header.split(','))
        for ind, entry in enumerate(s_list):
            s_list[ind] = entry.replace('\n', '').split(',')
            s_list[ind].append('')  # Para o campo id que será preenchido

        for ind, entry in enumerate(s_list):
            try:
                s_list[ind][0] = User.objects.get(link=entry[0]).pk
                s_list[ind][1] = User.objects.get(link=entry[1]).pk
            except User.DoesNotExist:
                continue
            dataset.append(s_list[ind])

        result = friends_resource.import_data(dataset, dry_run=True, raise_errors=True)  # Test the data import
        print("HAS ERRORS:", result.has_errors())

        if not result.has_errors():
            friends_resource.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'crudapp/import_db.html')

def import_db_likes_movie(request):
    if request.method == 'POST':
        movie_resource = LikesMovieResource()
        new_movies = request.FILES['myfile']
        s = new_movies.read().decode("utf-8")
        s_list = s.split('\r')
        header = s_list.pop(0)  # Header
        header += ',id'  # Adiciona id ao header (necessário)
        s_list.pop()  # '\n' (lixo)
        dataset = Dataset(headers=header.split(','))
        for ind, entry in enumerate(s_list):
            s_list[ind] = entry.replace('\n', '').split(',')
            s_list[ind].append('')  # Para o campo id que será preenchido

        for ind, entry in enumerate(s_list):
            try:
                s_list[ind][0] = User.objects.get(link=entry[0]).pk
            except User.DoesNotExist:
                continue
            dataset.append(s_list[ind])

        result = movie_resource.import_data(dataset, dry_run=True, raise_errors=True)  # Test the data import
        print("HAS ERRORS:", result.has_errors())

        if not result.has_errors():
            movie_resource.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'crudapp/import_db.html')

def import_db_likes_music(request):
    if request.method == 'POST':
        music_resource = LikesMusicResource()
        new_music = request.FILES['myfile']
        s = new_music.read().decode("utf-8")
        s_list = s.split('\r')
        header = s_list.pop(0)  # Header
        header += ',id'  # Adiciona id ao header (necessário)
        s_list.pop()  # '\n' (lixo)
        dataset = Dataset(headers=header.split(','))
        for ind, entry in enumerate(s_list):
            s_list[ind] = entry.replace('\n', '').split(',')
            s_list[ind].append('')  # Para o campo id que será preenchido

        for ind, entry in enumerate(s_list):
            try:
                s_list[ind][0] = User.objects.get(link=entry[0]).pk
            except User.DoesNotExist:
                continue
            dataset.append(s_list[ind])

        result = music_resource.import_data(dataset, dry_run=True, raise_errors=True)  # Test the data import
        print("HAS ERRORS:", result.has_errors())

        if not result.has_errors():
            music_resource.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'crudapp/import_db.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('crudapp:main_page')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

def add_movie_by_click(request):
    print(request.GET)
    return redirect('crudapp:main_page')


class UserListView(ListView):
    model = User
    template_name = 'crudapp/list_users.html'
    ordering = ['first_name']


class NewUserView(CreateView):
    form_class = SignUpForm
    template_name = 'crudapp/form_user.html'

    def post(self, request):
        form = self.get_form()
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('crudapp:user_page', username=username)
        else:
            return self.form_invalid(form)


class MainPageView(TemplateView):
    def get(self, request):
        context = {}
        if str(request.user) != 'AnonymousUser':
            self.user = request.user
            context = self.get_context_data()
        return render(request, 'crudapp/main_page.html', context)

    def get_context_data(self):
        context = {'movie_recommendations': self.get_recommended_movie(),
                   'music_recommendations': self.get_recommended_music()}
        return context

    def get_recommended_movie(self):
        user = self.user
        liked_genres = {}
        liked_movies = LikesMovie.objects.filter(user1=user)
        total_likes = len(liked_movies)
        if total_likes == 0:
            return None
        for relation in liked_movies:
            m = Movie.objects.get(pk=relation.movie_id)
            if m.genero not in liked_genres:
                liked_genres.update({m.genero: 1})
            else:
                liked_genres[m.genero] += 1

        recomendation = []
        sorted_genres = sorted(liked_genres.items(), key=lambda x: x[1])
        n = len(sorted_genres)
        if n == 0:
            recomendation = None
        elif n == 1:
            movies = Movie.objects.filter(genero=sorted_genres[0][0])  # Filmes do gênero
            not_liked_relation = LikesMovie.objects.exclude(user1=user).values('movie_id').distinct()
            not_liked_yet = movies.filter(pk__in=not_liked_relation).exclude(pk__in=liked_movies.values('movie_id'))
            recommended = not_liked_yet.exclude(pk__in=liked_movies).order_by("?").first()
            if recommended is not None:
                recomendation.append(recommended)
        elif n >= 2:
            for item in sorted_genres[-2:]:
                movies = Movie.objects.filter(genero=item[0])  # Filmes do gênero
                not_liked_relation = LikesMovie.objects.exclude(user1=user).values('movie_id').distinct()
                not_liked_yet = movies.filter(pk__in=not_liked_relation).exclude(pk__in=liked_movies.values('movie_id'))
                recommended = not_liked_yet.exclude(pk__in=liked_movies).order_by("?").first()
                if recommended is not None:

07- Análise e Data Mining/crudBD/crudapp/templates/crudapp/_modal.html
{% load static %}

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

<script src="{% static 'crudapp/assets/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'crudapp/assets/js/popper.min.js' %}"></script>
<script src="{% static 'crudapp/assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>

07- Análise e Data Mining/crudBD/crudapp/templates/crudapp/add_friend.html
{% extends 'crudapp/base_generic.html' %}
{% block title %}<h1>Adicionar Amigos</h1>{% endblock %}

{% block body %}

    <p>Adicionando amigos de {{ user.first_name }}</p>

    <h3>Amigos</h3>
    <ul>
    {% for friend in friends %}
        <li>{{ friend.first_name }} ({{ friend.first_name }})</li>
    {% empty %}
        <li>Você não tem amigos</li>
    {% endfor %}
    </ul>

    <h3>Outros Usuários</h3> <p>(clique para adicionar)</p>
    <ul>
    {% for other_user in not_friends %}
        <li><a href="{% url 'crudapp:add_friend' user.pk other_user.pk %}">{{ other_user.first_name }} ({{ other_user.first_name }})</a></li>
    {% empty %}
        <li>Você é amigo de todas as pessoas cadastradas na rede.</li>
    {% endfor %}
    </ul>

    <form action="{% url 'crudapp:user_page' user.username %}">
        <button type="submit">Voltar</button>
    </form>

{% endblock %}

07- Análise e Data Mining/crudBD/crudapp/templates/crudapp/add_movie.html
{% extends 'crudapp/base_generic.html' %}

{% block title %}<h1>Adicionar Filme</h1>{% endblock %}

{% block body %}

    <p>Adicionando filmes para o usuário: {{ user.username }}</p>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar" />
    </form>

    <form action="{% url 'crudapp:user_page' user.username %}">
        <button type="submit">Voltar</button>
    </form>

{% endblock %}

07- Análise e Data Mining/crudBD/crudapp/templates/crudapp/add_music.html
{% extends 'crudapp/base_generic.html' %}

{% block title %}<h1>Adicionar Música</h1>{% endblock %}

{% block body %}

    <p>Adicionando músicas para o usuário: {{ user.nome }}</p>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar" />
    </form>

    <form action="{% url 'crudapp:user_page' user.username %}">
        <button type="submit">Voltar</button>
    </form>

{% endblock %}

07- Análise e Data Mining/crudBD/crudapp/templates/crudapp/average_page.html
{% extends 'crudapp/base_generic.html' %}

{% block title %}<h1>Médias e desvios padrão</h1>{% endblock %}

{% block body %}

Média das avaliações dos artistas: {{notas_music}} <br>
Desvio padrão das avaliações dos artistas: {{desvio_music}} <br>
Média das avaliações dos filmes: {{notas_films}} <br>
Desvio padrão das avaliações dos filmes: {{desvio_films}} <br>


    <form action="{% url 'crudapp:statistics_page' %}">
        <button type="submit">Voltar</button>
	</form>
</div>



{% endblock %}

07- Análise e Data Mining/crudBD/crudapp/templates/crudapp/barra_lateral.html
<style>
    .sidenav {
        height: 100%;
        width: 110px;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        background-color: #565656;
        overflow-x: hidden;

    }
    .sidenav a {
        alignment: center;
        padding: 1px 1px 1px 1px;
        text-decoration: none;
        font-size: 25px;
        color: #000000;
        display: block;
    }
    .sidenav a:hover {
        background-color: #000000;
    }

    .Links{
        text-align: center;
        padding-top: 10px;
        font-size: 11.5px;
        color: #ffffff;
        font-family: "Segoe UI",Arial,sans-serif;;
    }
    .btn_link{
        width: auto;
        border: none;
        display: inline;
    }
    @media screen and (max-height: 450px) {
        .sidenav {padding-top: 15px;}
        .sidenav a {font-size: 18px;}
    }
</style>

<div class="sidenav">
    <a class="btn_link" href="{% url 'crudapp:main_page' %}"><p class="Links" ><b>HOME</b></p></a>
    {% if request.user.is_authenticated %}
        <a class="btn_link" href="{% url 'crudapp:user_page' request.user.username %}"><p class="Links" ><b>PÁGINA PESSOAL</b></p></a>
        <a class="btn_link" href="{% url 'crudapp:user_list_page' %}"><p class="Links" ><b>USUÁRIOS</b></p></a>
        <a class="btn_link" href="{% url 'crudapp:statistics_page' %}"><p class="Links" ><b>ESTATÍSTICAS</b></p></a>
    {% endif %}
</div>

07- Análise e Data Mining/crudBD/crudapp/templates/crudapp/barra_superior.html
{% load static %}

<script type="text/javascript">
    $(function () {
        $(".login-btn").modalForm({formURL: "{% url 'crudapp:login' %}"});
    });
</script>

<style>
    .divTituloPag {
        background-color: #eee;
        height: 100px;
        width: 100%;
    }
    .btn_Login{
        position: relative;
        left: 55px;
    }
    .btn_Logout{
        position: relative;

        left: 55px;
    }
</style>

<div id="titulo-pag" class="divTituloPag">
    <div style="display: inline-block; vertical-align: top; height: 100%; "><a href="{% url 'crudapp:main_page' %}"><img alt="Whatever logo" style="padding: 5px; width: auto; max-height: 100%; " src="{% static 'crudapp/images/whatever logo.jpg' %}"></a></div>
    <div style="display: inline-block; position: relative; left: 0%; top: 25%;"><h2 style=" margin-left: 70px; text-align: center; ">Whatever Social Media</h2></div>
    <div style="display: table; float: right; height: 100%; padding-right: 10px;">
        {% if request.user.is_authenticated %}
            <p style="display: table-cell; position: relative; top: 25%; left: 5%; font-weight: bold;">Bem vind@, {{ request.user.first_name }}!</p>
            <form action="{% url 'crudapp:logout' %}" style="display: table-cell; position: relative; top: 25%;">
                <button class="botaoPadrao btn_Logout" style="margin-right: 50px;" ><b>Logout</b></button>
            </form>
        {% else %}
            <button class="login-btn botaoPadrao btn_Login" style="margin-right: 50px; margin-top: 25%;"  type="submit" name="button">Log in</button>
        {% endif %}
    </div>
</div>

07- Análise e Data Mining/crudBD/crudapp/templates/crudapp/base_generic.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'crudapp/assets/css/bootstrap.min.css' %}">
    <!--<link rel="stylesheet" href="{% static 'assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">-->
    <!--<link rel="stylesheet" type = "text/css" href="{% static 'crudapp/assets/css/crudapp.css' %}">-->
    <meta charset="UTF-8">
    <title>{% block page_title %}Whatever Social Media{% endblock %}</title>

    <style>
        .error_message {
            color: red;
            font-weight: bold;
        }
        .main {
            margin-left: 110px;
        }
        .full_page{
            background-color: lightgrey;
        }
        .main_body {
            margin-left: 50px;
        }
        .botaoPadrao{
            font-size: 15px;
            padding: 5px;
            padding-left: 15px;
            padding-right: 15px;
            border-radius: 5px;
            border: solid 1px black;
            background-color: #565656;
            color: white;
        }
        .botaoPadrao:hover{
            border: solid 1px black;
            background-color: black;
            cursor: pointer;
        }
    </style>
    {% block style %}
    {% endblock %}

    <script type="text/javascript">
        $(function () {
            $(".upd").each(function () {
                $(this).modalForm({formURL: $(this).data('id')});
            });
            $(".delete-btn").each(function () {
                $(this).modalForm({formURL: $(this).data('id')});
            })
        });
    </script>
    {% block script %}
    {% endblock %}

    {% block head %}
    {% endblock %}
</head>

<body class="full_page">
    {% include "crudapp/_modal.html" %}
    {% include "crudapp/barra_lateral.html" %}
    <div class="main">
        {% include "crudapp/barra_superior.html" %}
        <div class="main_body">
            {% block title %}{% endblock %}
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        {% if message.tags == 'error' %}
                            <li class="error_message">{{ message }}</li>
                        {% else %}
                            <li>{{ message }}</li>
                        {% endif %}
                    {% endfor %}
                </ul>
            {% endif %}

            {% block body %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

07- Análise e Data Mining/crudBD/crudapp/templates/crudapp/graphics_page.html
{% extends 'crudapp/base_generic.html' %}

{% block title %}<h1>Gráficos</h1>{% endblock %}

{% block body %}

    <img src="data:image/png;base64,{{ img }}" />

    <img src="data:image/png;base64,{{ img2 }}" />

    <img src="data:image/png;base64,{{ img3 }}" />


    <form action="{% url 'crudapp:statistics_page' %}">
        <button type="submit">Voltar</button>
	</form>

{% endblock %}

07- Análise e Data Mining/crudBD/crudapp/templates/crudapp/import_db.html
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

07- Análise e Data Mining/crudBD/crudapp/templates/crudapp/popularity_page.html
{% extends 'crudapp/base_generic.html' %}

{% block title %}<h1>Popularidade</h1>{% endblock %}

{% block body %}

<p>Artistas mais populares:</p>
    <ul>
    {% for item in populares_musica %}
        <li><a>{{ item.link }} - {{item.count}}</a></li>
    {% empty %}
        <li>Nenhum usuário criado.</li>
    {% endfor %}
    </ul>

    <p>Filmes mais populares:</p>
    <ul>
    {% for item in populares_filmes %}
        <li><a>{{ item.link }} - {{item.count}}</a></li>
    {% empty %}
        <li>Nenhum usuário criado.</li>
    {% endfor %}
    </ul>

    <form action="{% url 'crudapp:statistics_page' %}">
        <button type="submit">Voltar</button>
	</form>
</div>
{% endblock %}

07- Análise e Data Mining/crudBD/crudapp/templates/crudapp/statistics_page.html
{% extends 'crudapp/base_generic.html' %}

{% block title %}<h1>Estatísticas</h1>{% endblock %}

{% block body %}

<li><a href="{% url 'crudapp:average_page' %}">Médias e desvios padrão</a></li>
<li><a href="{% url 'crudapp:ratings_page' %}">Melhores ratings</a></li>
<li><a href="{% url 'crudapp:popularity_page' %}">Popularidade das bandas e filmes</a></li>
<!--<li><a href="{% url 'crudapp:conhecidos_page' %}">Operações com conhecidos</a></li>-->

<!--<li><a href="{% url 'crudapp:graphics_page' %}">Gráficos</a></li>-->

<div>

    <form action="{% url 'crudapp:main_page' %}">
        <button type="submit">Voltar</button>
	</form>
</div>



{% endblock %}